/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subproject1;

public class MyUnit {

    public String concatenate(String one, String two){
        return one + two;
    }
}