/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.multiproject;

import org.junit.jupiter.api.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class LombokExTest {
    @Test public void testLombokEx() {
        LombokEx classUnderTest = new LombokEx();
        classUnderTest.setField("aaa");
        assertEquals("aaa", classUnderTest.getField());
    }
}
