/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subproject1;

import org.junit.jupiter.api.Test;
import static org.junit.Assert.*;

public class MyUnitTest {

    @Test
    public void testConcatenate() {
        MyUnit myUnit = new MyUnit();

        String result = myUnit.concatenate("one", "two");

        assertEquals("onetwo", result);

    }
}
